### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST localhost:8080/api/project
Content-Type: application/json

{
  "project": {
    "name": "프로젝트1",
    "status": "ACTIVATION"
  },

  "member": {
    "name": "김주혁",
    "email": "asdf@gmail.com",
    "role" : "ADMIN"
  }
}